version: 2

updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
