name: Review

on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: review-${{ github.base_ref }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  review:
    name: Review Flutter PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: 'stable'
          cache: true

      - name: Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Check Format
        run: dart format -l 120 --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test
